/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package calcu;

/**
 *
 * @author Job_M
 */
public class Interface extends javax.swing.JDialog {

    private boolean igual, inicio = true,operacion1,operacion2;
    private double a,b,c,memoria = 0,resultado,valor1,valor2;
    private String cadena,funciones,tipoOperaciones;
    
    
    
    public Interface(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        princi = new javax.swing.JLabel();
        prev = new javax.swing.JLabel();
        jbpunto = new javax.swing.JButton();
        jbigual = new javax.swing.JButton();
        jbsum = new javax.swing.JButton();
        jbres = new javax.swing.JButton();
        jbmult = new javax.swing.JButton();
        jbdiv = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jbraiz = new javax.swing.JButton();
        jbce = new javax.swing.JButton();
        jbc = new javax.swing.JButton();
        jbtan = new javax.swing.JButton();
        jbcos = new javax.swing.JButton();
        jbsin = new javax.swing.JButton();
        jbartan = new javax.swing.JButton();
        jbarcos = new javax.swing.JButton();
        jbarsin = new javax.swing.JButton();
        jbporc = new javax.swing.JButton();
        jb1x = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb1.setText("1");
        jb1.setBorder(null);
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb2.setText("2");
        jb2.setBorder(null);
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jb3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb3.setText("3");
        jb3.setBorder(null);
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jb4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb4.setText("4");
        jb4.setBorder(null);
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });

        jb5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb5.setText("5");
        jb5.setBorder(null);
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });

        jb7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb7.setText("7");
        jb7.setBorder(null);
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });

        jb8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb8.setText("8");
        jb8.setBorder(null);
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });

        jb9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb9.setText("9");
        jb9.setBorder(null);
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });

        jb0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb0.setText("0");
        jb0.setBorder(null);
        jb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb0ActionPerformed(evt);
            }
        });

        jb6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb6.setText("6");
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });

        princi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        princi.setForeground(new java.awt.Color(255, 153, 51));
        princi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        princi.setText("0");
        princi.setFocusable(false);

        prev.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prev.setFocusable(false);

        jbpunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbpunto.setForeground(new java.awt.Color(255, 153, 51));
        jbpunto.setText(".");
        jbpunto.setBorder(null);
        jbpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpuntoActionPerformed(evt);
            }
        });

        jbigual.setBackground(new java.awt.Color(255, 153, 51));
        jbigual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbigual.setForeground(new java.awt.Color(255, 255, 255));
        jbigual.setText("=");
        jbigual.setBorder(null);
        jbigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbigualActionPerformed(evt);
            }
        });

        jbsum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsum.setForeground(new java.awt.Color(255, 153, 51));
        jbsum.setText("+");
        jbsum.setBorder(null);
        jbsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsumActionPerformed(evt);
            }
        });

        jbres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbres.setForeground(new java.awt.Color(255, 153, 51));
        jbres.setText("-");
        jbres.setBorder(null);
        jbres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbresActionPerformed(evt);
            }
        });

        jbmult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbmult.setForeground(new java.awt.Color(255, 153, 51));
        jbmult.setText("x");
        jbmult.setBorder(null);
        jbmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmultActionPerformed(evt);
            }
        });

        jbdiv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbdiv.setForeground(new java.awt.Color(255, 153, 51));
        jbdiv.setText("/");
        jbdiv.setBorder(null);
        jbdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdivActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 153, 51));
        jButton18.setText("x²");
        jButton18.setBorder(null);

        jbraiz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbraiz.setForeground(new java.awt.Color(255, 153, 51));
        jbraiz.setText("√");
        jbraiz.setBorder(null);
        jbraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbraizActionPerformed(evt);
            }
        });

        jbce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbce.setForeground(new java.awt.Color(255, 153, 51));
        jbce.setText("CE");
        jbce.setBorder(null);
        jbce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbceActionPerformed(evt);
            }
        });

        jbc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbc.setForeground(new java.awt.Color(255, 153, 51));
        jbc.setText("C");
        jbc.setBorder(null);
        jbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcActionPerformed(evt);
            }
        });

        jbtan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtan.setForeground(new java.awt.Color(255, 153, 51));
        jbtan.setText("tan");

        jbcos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbcos.setForeground(new java.awt.Color(255, 153, 51));
        jbcos.setText("cos");

        jbsin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsin.setForeground(new java.awt.Color(255, 153, 51));
        jbsin.setText("sin");
        jbsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsinActionPerformed(evt);
            }
        });

        jbartan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbartan.setForeground(new java.awt.Color(255, 153, 51));
        jbartan.setText("tan¹");

        jbarcos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbarcos.setForeground(new java.awt.Color(255, 153, 51));
        jbarcos.setText("cos¹");

        jbarsin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbarsin.setForeground(new java.awt.Color(255, 153, 51));
        jbarsin.setText("sin¹");

        jbporc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbporc.setForeground(new java.awt.Color(255, 153, 51));
        jbporc.setText("%");
        jbporc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbporcActionPerformed(evt);
            }
        });

        jb1x.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb1x.setForeground(new java.awt.Color(255, 153, 51));
        jb1x.setText("1/x");
        jb1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1xActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbraiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbpunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jb0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbporc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbsin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb1x, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbarsin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jb6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbigual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbce, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbcos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jbarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbartan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jbtan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbsum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbmult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbdiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(princi, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(princi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbartan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbarcos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbarsin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb1x, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbporc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbcos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbsin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbraiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbmult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbsum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("1");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"1");
        }
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("7");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"7");
        }
    }//GEN-LAST:event_jb7ActionPerformed

    private void jbraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbraizActionPerformed
        valor1 = Double.parseDouble(princi.getText());
        if (valor1 >= 0){
            prev.setText("sqrt( "+valor1+" )");
            princi.setText(Math.sqrt(valor1)+ "");
        }else{
            princi.setText("error pai");
        }
    }//GEN-LAST:event_jbraizActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("2");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"2");
        }
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("3");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"3");
        }
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
if (inicio == true){
            princi.setText("");
            princi.setText("4");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"4");
        }    }//GEN-LAST:event_jb4ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
if (inicio == true){
            princi.setText("");
            princi.setText("5");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"5");
        }    }//GEN-LAST:event_jb5ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("6");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"6");
        }
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("8");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"8");
        }
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("9");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"9");
        }
    }//GEN-LAST:event_jb9ActionPerformed

    private void jbpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpuntoActionPerformed
        if (princi.getText().contains(".")){
            
        }else{
            princi.setText(princi.getText()+".");
            inicio = false;
        }
    }//GEN-LAST:event_jbpuntoActionPerformed
    
    private void Operaciones(double valor1,double valor2){
        
        switch(tipoOperaciones){
            case "+":
                resultado = valor1 + valor2;
                princi.setText(resultado + "");
                valor1 = Double.parseDouble(princi.getText());
                break;
                
            case "-":
                resultado = valor1 - valor2;
                princi.setText(resultado + "");
                valor1 = Double.parseDouble(princi.getText());
                break;
                
            case "*":
                resultado = valor1 * valor2;
                princi.setText(resultado + "");
                valor1 = Double.parseDouble(princi.getText());
                break;
              
            case "/":
                if (valor2 == 0){
                    princi.setText("error pai");
                    break;
                }else{
                    resultado = valor1 / valor2;
                    princi.setText(resultado + "");
                    valor1 = Double.parseDouble(princi.getText());
                    break;
                }         
        }
    }
    
    private void jbigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbigualActionPerformed
        inicio = true;
        operacion1 = true;
        if(igual = true){
            if (tipoOperaciones == null){
                
            }else{
                valor2 = Double.parseDouble(princi.getText());
                prev.setText(prev.getText()+princi.getText());
                Operaciones(valor1,valor2);
                igual = false;
                }
            }else{
               prev.setText("");
               Operaciones(valor1,valor2);
        }
    }//GEN-LAST:event_jbigualActionPerformed

    private void jbsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsumActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true){
            valor1 = Double.parseDouble(princi.getText());
            prev.setText("");
            prev.setText(princi.getText()+ "+");
            operacion1 = false;
        }else{
            if (operacion2 = true){
                valor2 = Double.parseDouble(princi.getText());
                prev.setText("");
                prev.setText(princi.getText()+ "+");
                operacion2 = false;
            }else{
                prev.setText(princi.getText()+ "+");
                Operaciones(resultado,valor2);
            }
        }
        tipoOperaciones = "+";
    }//GEN-LAST:event_jbsumActionPerformed

    private void jbresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbresActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true){
            valor1 = Double.parseDouble(princi.getText());
            prev.setText("");
            prev.setText(princi.getText()+ "-");
            operacion1 = false;
        }else{
            if (operacion2 = true){
                valor2 = Double.parseDouble(princi.getText());
                prev.setText("");
                prev.setText(princi.getText()+ "-");
                operacion2 = false;
            }else{
                prev.setText(princi.getText()+ "-");
                Operaciones(resultado,valor2);
            }
        }
        tipoOperaciones = "-";
    }//GEN-LAST:event_jbresActionPerformed

    private void jbmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmultActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true){
            valor1 = Double.parseDouble(princi.getText());
            prev.setText("");
            prev.setText(princi.getText()+ "*");
            operacion1 = false;
        }else{
            if (operacion2 = true){
                valor2 = Double.parseDouble(princi.getText());
                prev.setText("");
                prev.setText(princi.getText()+ "*");
                operacion2 = false;
            }else{
                prev.setText(princi.getText()+ "*");
                Operaciones(resultado,valor2);
            }
        }
        tipoOperaciones = "*";
    }//GEN-LAST:event_jbmultActionPerformed

    private void jbdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdivActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true){
            valor1 = Double.parseDouble(princi.getText());
            prev.setText("");
            prev.setText(princi.getText()+ "/");
            operacion1 = false;
        }else{
            if (operacion2  = true){
                valor2 = Double.parseDouble(princi.getText());
                prev.setText("");
                prev.setText(princi.getText()+ "/");
                operacion2 = false;
            }else{
                prev.setText(princi.getText()+ "/");
                Operaciones(resultado,valor2);
            }
        }
        tipoOperaciones = "/";
    }//GEN-LAST:event_jbdivActionPerformed

    private void jbporcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbporcActionPerformed
        valor2 = Double.parseDouble(princi.getText());
        prev.setText(prev.getText()+princi.getText());
        princi.setText((valor1*valor2)/100 +"");
        igual = true;
    }//GEN-LAST:event_jbporcActionPerformed

    private void jb1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1xActionPerformed
        valor1 = Double.parseDouble(princi.getText());
        prev.setText("reciproc( "+valor1+" )");
        princi.setText(1/valor1+"");
    }//GEN-LAST:event_jb1xActionPerformed

    private void jbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcActionPerformed
        princi.setText("0");
        prev.setText("");
        inicio = true;
        funciones = "";
        operacion1 = true;
        operacion2 = true;
        igual = true;
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
        
    }//GEN-LAST:event_jbcActionPerformed

    private void jbceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbceActionPerformed
        princi.setText("0");
        prev.setText("");
        inicio = true;
        funciones = "";
    }//GEN-LAST:event_jbceActionPerformed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        if (inicio == true){
            princi.setText("");
            princi.setText("0");
            inicio = false;
        }else{
            princi.setText(princi.getText()+"0");
        }               
    }//GEN-LAST:event_jb0ActionPerformed

    private void jbsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Interface dialog = new Interface(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb1x;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbarcos;
    private javax.swing.JButton jbarsin;
    private javax.swing.JButton jbartan;
    private javax.swing.JButton jbc;
    private javax.swing.JButton jbce;
    private javax.swing.JButton jbcos;
    private javax.swing.JButton jbdiv;
    private javax.swing.JButton jbigual;
    private javax.swing.JButton jbmult;
    private javax.swing.JButton jbporc;
    private javax.swing.JButton jbpunto;
    private javax.swing.JButton jbraiz;
    private javax.swing.JButton jbres;
    private javax.swing.JButton jbsin;
    private javax.swing.JButton jbsum;
    private javax.swing.JButton jbtan;
    private javax.swing.JLabel prev;
    private javax.swing.JLabel princi;
    // End of variables declaration//GEN-END:variables
}
